# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import alumno_pb2 as alumno__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in alumno_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlumnoServiceStub(object):
    """Funciones del servidor

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Registrar = channel.unary_unary(
                '/alumnos.AlumnoService/Registrar',
                request_serializer=alumno__pb2.RegistrarRequest.SerializeToString,
                response_deserializer=alumno__pb2.RegistrarResponse.FromString,
                _registered_method=True)
        self.Consultar = channel.unary_unary(
                '/alumnos.AlumnoService/Consultar',
                request_serializer=alumno__pb2.ConsultarRequest.SerializeToString,
                response_deserializer=alumno__pb2.Alumno.FromString,
                _registered_method=True)
        self.Actualizar = channel.unary_unary(
                '/alumnos.AlumnoService/Actualizar',
                request_serializer=alumno__pb2.ActualizarRequest.SerializeToString,
                response_deserializer=alumno__pb2.Respuesta.FromString,
                _registered_method=True)
        self.Eliminar = channel.unary_unary(
                '/alumnos.AlumnoService/Eliminar',
                request_serializer=alumno__pb2.EliminarRequest.SerializeToString,
                response_deserializer=alumno__pb2.Respuesta.FromString,
                _registered_method=True)
        self.BuscarPorCriterio = channel.unary_stream(
                '/alumnos.AlumnoService/BuscarPorCriterio',
                request_serializer=alumno__pb2.BuscarRequest.SerializeToString,
                response_deserializer=alumno__pb2.Alumno.FromString,
                _registered_method=True)
        self.ListarTodos = channel.unary_stream(
                '/alumnos.AlumnoService/ListarTodos',
                request_serializer=alumno__pb2.ListarRequest.SerializeToString,
                response_deserializer=alumno__pb2.Alumno.FromString,
                _registered_method=True)


class AlumnoServiceServicer(object):
    """Funciones del servidor

    """

    def Registrar(self, request, context):
        """Operaciones 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consultar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Actualizar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Eliminar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPorCriterio(self, request, context):
        """Operaciones donde hay interacción entre cliente y servidor

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlumnoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Registrar': grpc.unary_unary_rpc_method_handler(
                    servicer.Registrar,
                    request_deserializer=alumno__pb2.RegistrarRequest.FromString,
                    response_serializer=alumno__pb2.RegistrarResponse.SerializeToString,
            ),
            'Consultar': grpc.unary_unary_rpc_method_handler(
                    servicer.Consultar,
                    request_deserializer=alumno__pb2.ConsultarRequest.FromString,
                    response_serializer=alumno__pb2.Alumno.SerializeToString,
            ),
            'Actualizar': grpc.unary_unary_rpc_method_handler(
                    servicer.Actualizar,
                    request_deserializer=alumno__pb2.ActualizarRequest.FromString,
                    response_serializer=alumno__pb2.Respuesta.SerializeToString,
            ),
            'Eliminar': grpc.unary_unary_rpc_method_handler(
                    servicer.Eliminar,
                    request_deserializer=alumno__pb2.EliminarRequest.FromString,
                    response_serializer=alumno__pb2.Respuesta.SerializeToString,
            ),
            'BuscarPorCriterio': grpc.unary_stream_rpc_method_handler(
                    servicer.BuscarPorCriterio,
                    request_deserializer=alumno__pb2.BuscarRequest.FromString,
                    response_serializer=alumno__pb2.Alumno.SerializeToString,
            ),
            'ListarTodos': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarTodos,
                    request_deserializer=alumno__pb2.ListarRequest.FromString,
                    response_serializer=alumno__pb2.Alumno.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alumnos.AlumnoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alumnos.AlumnoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlumnoService(object):
    """Funciones del servidor

    """

    @staticmethod
    def Registrar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/Registrar',
            alumno__pb2.RegistrarRequest.SerializeToString,
            alumno__pb2.RegistrarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consultar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/Consultar',
            alumno__pb2.ConsultarRequest.SerializeToString,
            alumno__pb2.Alumno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Actualizar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/Actualizar',
            alumno__pb2.ActualizarRequest.SerializeToString,
            alumno__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Eliminar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alumnos.AlumnoService/Eliminar',
            alumno__pb2.EliminarRequest.SerializeToString,
            alumno__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarPorCriterio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alumnos.AlumnoService/BuscarPorCriterio',
            alumno__pb2.BuscarRequest.SerializeToString,
            alumno__pb2.Alumno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alumnos.AlumnoService/ListarTodos',
            alumno__pb2.ListarRequest.SerializeToString,
            alumno__pb2.Alumno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
