/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "incremento.h"


void
programaincremento_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  incremento_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMAINCREMENTO, INCREMENTOVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	printf("El resultado es : %d", *result_1)
#endif	/* DEBUG */

	result_1 = incremento_1(&incremento_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programaincremento_1 (host);
exit (0);
}
