/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INCREMENTO_H_RPCGEN
#define _INCREMENTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAMAINCREMENTO 0x20000001
#define INCREMENTOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define incremento 1
extern  int * incremento_1(int *, CLIENT *);
extern  int * incremento_1_svc(int *, struct svc_req *);
extern int programaincremento_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define incremento 1
extern  int * incremento_1();
extern  int * incremento_1_svc();
extern int programaincremento_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INCREMENTO_H_RPCGEN */
