/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "incremento.h"

int *
incremento_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	result =* argp+ 3;
	
	/*
	 * insert server code here
	 */
	
	return &result;
}
