# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alumno.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alumno.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61lumno.proto\x12\x07\x61lumnos\"f\n\x06\x41lumno\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x04 \x01(\x05\x12\r\n\x05\x63urso\x18\x05 \x01(\t\x12\x11\n\tdireccion\x18\x06 \x01(\t\"d\n\x10RegistrarRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x61pellido\x18\x02 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x03 \x01(\x05\x12\r\n\x05\x63urso\x18\x04 \x01(\t\x12\x11\n\tdireccion\x18\x05 \x01(\t\"?\n\x11RegistrarResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"\x1e\n\x10\x43onsultarRequest\x12\n\n\x02id\x18\x01 \x01(\t\"q\n\x11\x41\x63tualizarRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x04 \x01(\x05\x12\r\n\x05\x63urso\x18\x05 \x01(\t\x12\x11\n\tdireccion\x18\x06 \x01(\t\"\x1d\n\x0f\x45liminarRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\tRespuesta\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"0\n\rBuscarRequest\x12\r\n\x05\x63\x61mpo\x18\x01 \x01(\t\x12\x10\n\x08\x63riterio\x18\x02 \x01(\t\"\x0f\n\rListarRequest2\xfe\x02\n\rAlumnoService\x12\x42\n\tRegistrar\x12\x19.alumnos.RegistrarRequest\x1a\x1a.alumnos.RegistrarResponse\x12\x37\n\tConsultar\x12\x19.alumnos.ConsultarRequest\x1a\x0f.alumnos.Alumno\x12<\n\nActualizar\x12\x1a.alumnos.ActualizarRequest\x1a\x12.alumnos.Respuesta\x12\x38\n\x08\x45liminar\x12\x18.alumnos.EliminarRequest\x1a\x12.alumnos.Respuesta\x12>\n\x11\x42uscarPorCriterio\x12\x16.alumnos.BuscarRequest\x1a\x0f.alumnos.Alumno0\x01\x12\x38\n\x0bListarTodos\x12\x16.alumnos.ListarRequest\x1a\x0f.alumnos.Alumno0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alumno_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALUMNO']._serialized_start=25
  _globals['_ALUMNO']._serialized_end=127
  _globals['_REGISTRARREQUEST']._serialized_start=129
  _globals['_REGISTRARREQUEST']._serialized_end=229
  _globals['_REGISTRARRESPONSE']._serialized_start=231
  _globals['_REGISTRARRESPONSE']._serialized_end=294
  _globals['_CONSULTARREQUEST']._serialized_start=296
  _globals['_CONSULTARREQUEST']._serialized_end=326
  _globals['_ACTUALIZARREQUEST']._serialized_start=328
  _globals['_ACTUALIZARREQUEST']._serialized_end=441
  _globals['_ELIMINARREQUEST']._serialized_start=443
  _globals['_ELIMINARREQUEST']._serialized_end=472
  _globals['_RESPUESTA']._serialized_start=474
  _globals['_RESPUESTA']._serialized_end=517
  _globals['_BUSCARREQUEST']._serialized_start=519
  _globals['_BUSCARREQUEST']._serialized_end=567
  _globals['_LISTARREQUEST']._serialized_start=569
  _globals['_LISTARREQUEST']._serialized_end=584
  _globals['_ALUMNOSERVICE']._serialized_start=587
  _globals['_ALUMNOSERVICE']._serialized_end=969
# @@protoc_insertion_point(module_scope)
