/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Dato {
	int a;
	int b;
};
typedef struct Dato Dato;

#define CALCULADORA 0x20000004
#define VER_CALCU 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(Dato *, CLIENT *);
extern  int * suma_1_svc(Dato *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Dato (XDR *, Dato*);

#else /* K&R C */
extern bool_t xdr_Dato ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
