/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"

int *
suma_1_svc(Dato *argp, struct svc_req *rqstp)
{
	static int  result;

	result= argp ->a + argp ->b;

	return &result;
}

int *
rest_1_svc(Dato *argp, struct svc_req *rqstp)
{
	static int  result;

	result= argp ->a - argp ->b;

	return &result;
}

int *
multiplicar_1_svc(Dato *argp, struct svc_req *rqstp)
{
	static int  result;

	result= argp ->a * argp ->b;

	return &result;
}

int *
dividir_1_svc(Dato *argp, struct svc_req *rqstp)
{
	static int  result;

	result= argp ->a / argp ->b;

	return &result;
}
