/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"


void
calculadora_1(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	Dato  suma_1_arg;
	int  *result_2;
	Dato  rest_1_arg;
	int  *result_3;
	Dato  multiplicar_1_arg;
	int  *result_4;
	Dato  dividir_1_arg;

	suma_1_arg.a=a;
	suma_1_arg.b=b;

	rest_1_arg.a=a;
	rest_1_arg.b=b;

	multiplicar_1_arg.a=a;
	multiplicar_1_arg.b=b;

	dividir_1_arg.a=a;
	dividir_1_arg.b=b;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, VER_CALCU, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("El resultado de la suma es : %d + %d = %d ", a, b, *result_1 );
	}
	result_2 = rest_1(&rest_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("El resultado de la resta es : %d + %d = %d ", a, b, *result_2 );
	}
	result_3 = multiplicar_1(&multiplicar_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("El resultado de la multiplicacion es : %d + %d = %d ", a, b, *result_3 );
	}
	result_4 = dividir_1(&dividir_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("El resultado de la divison es : %d + %d = %d ", a, b, *result_4 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	int a=10;

	int b=5;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host, a, b);
exit (0);
}
