# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\"#\n\x0bSumaRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"!\n\x0cSumaResponse\x12\x11\n\tresultado\x18\x01 \x01(\x05\x32K\n\x0b\x43\x61lculadora\x12<\n\x05Sumar\x12\x18.calculadora.SumaRequest\x1a\x19.calculadora.SumaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMAREQUEST']._serialized_start=34
  _globals['_SUMAREQUEST']._serialized_end=69
  _globals['_SUMARESPONSE']._serialized_start=71
  _globals['_SUMARESPONSE']._serialized_end=104
  _globals['_CALCULADORA']._serialized_start=106
  _globals['_CALCULADORA']._serialized_end=181
# @@protoc_insertion_point(module_scope)
