/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "alumnos.h"

bool_t
xdr_alumno (XDR *xdrs, alumno *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->apellido, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->edad))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->curso, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_busqueda (XDR *xdrs, busqueda *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->curso, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado_busqueda (XDR *xdrs, resultado_busqueda *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case 0:
		 if (!xdr_alumno (xdrs, &objp->resultado_busqueda_u.al))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_alumno_nodo (XDR *xdrs, alumno_nodo *objp)
{
	register int32_t *buf;

	 if (!xdr_alumno (xdrs, &objp->al))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->sig, sizeof (alumno_nodo), (xdrproc_t) xdr_alumno_nodo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lista_alumnos (XDR *xdrs, lista_alumnos *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (alumno_nodo), (xdrproc_t) xdr_alumno_nodo))
		 return FALSE;
	return TRUE;
}
