/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ALUMNOS_H_RPCGEN
#define _ALUMNOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct alumno {
	int id;
	char *nombre;
	char *apellido;
	int edad;
	char *curso;
};
typedef struct alumno alumno;

struct busqueda {
	int id;
	char *nombre;
	char *curso;
};
typedef struct busqueda busqueda;

struct resultado_busqueda {
	int status;
	union {
		alumno al;
	} resultado_busqueda_u;
};
typedef struct resultado_busqueda resultado_busqueda;

struct alumno_nodo {
	alumno al;
	struct alumno_nodo *sig;
};
typedef struct alumno_nodo alumno_nodo;

typedef alumno_nodo *lista_alumnos;

#define REGISTROALUMNOS 0x20000001
#define REGISTROALUMNOS_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrar_alumno 1
extern  bool_t * registrar_alumno_1(alumno *, CLIENT *);
extern  bool_t * registrar_alumno_1_svc(alumno *, struct svc_req *);
#define buscar_alumno 2
extern  resultado_busqueda * buscar_alumno_1(busqueda *, CLIENT *);
extern  resultado_busqueda * buscar_alumno_1_svc(busqueda *, struct svc_req *);
#define actualizar_alumno 3
extern  bool_t * actualizar_alumno_1(alumno *, CLIENT *);
extern  bool_t * actualizar_alumno_1_svc(alumno *, struct svc_req *);
#define eliminar_alumno 4
extern  bool_t * eliminar_alumno_1(int *, CLIENT *);
extern  bool_t * eliminar_alumno_1_svc(int *, struct svc_req *);
#define listar_alumnos 5
extern  lista_alumnos * listar_alumnos_1(void *, CLIENT *);
extern  lista_alumnos * listar_alumnos_1_svc(void *, struct svc_req *);
extern int registroalumnos_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrar_alumno 1
extern  bool_t * registrar_alumno_1();
extern  bool_t * registrar_alumno_1_svc();
#define buscar_alumno 2
extern  resultado_busqueda * buscar_alumno_1();
extern  resultado_busqueda * buscar_alumno_1_svc();
#define actualizar_alumno 3
extern  bool_t * actualizar_alumno_1();
extern  bool_t * actualizar_alumno_1_svc();
#define eliminar_alumno 4
extern  bool_t * eliminar_alumno_1();
extern  bool_t * eliminar_alumno_1_svc();
#define listar_alumnos 5
extern  lista_alumnos * listar_alumnos_1();
extern  lista_alumnos * listar_alumnos_1_svc();
extern int registroalumnos_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_alumno (XDR *, alumno*);
extern  bool_t xdr_busqueda (XDR *, busqueda*);
extern  bool_t xdr_resultado_busqueda (XDR *, resultado_busqueda*);
extern  bool_t xdr_alumno_nodo (XDR *, alumno_nodo*);
extern  bool_t xdr_lista_alumnos (XDR *, lista_alumnos*);

#else /* K&R C */
extern bool_t xdr_alumno ();
extern bool_t xdr_busqueda ();
extern bool_t xdr_resultado_busqueda ();
extern bool_t xdr_alumno_nodo ();
extern bool_t xdr_lista_alumnos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ALUMNOS_H_RPCGEN */
